config/routes.rb
Rails.application.routes.draw do
  resources :prompts
  resources :activities
  resources :favor_items
  get 'admin' => 'admin#index'

  controller :activities do
    get 'activity_show' => :show_activity
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :prompts, dependent: :destroy

  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = prompts.find_by(product: product.id)

    if current_item
      # 查找到了，就啥都不干
    else
      # 没查找到，就创建 prompt
      current_item = prompts.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = line_items.find_by(product: product.id)

    if current_item
      # 查找到了，就数量增加 1
      current_item.quantity += 1
    else
      # 没查找到，就创建 line_item
      current_item = line_items.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/favor_item.rb
class FavorItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  # optional 表示外键可以为空
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    product.getDiscountPrice * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }

  has_many :line_items, dependent: :destroy

  validates :name, :address, :email, :phone, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # 对属性的检验
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {:greater_than_or_equal_to => 0.01}
  validates :title, uniqueness: true
  validates :image_url, format: {
    :with => %r{\.(gif|jpg|png)}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }

  # 与 line_item 关系
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :favor_items
  before_destroy :ensure_not_referenced_by_any_favor_item
  has_many :prompts, dependent: :destroy

  def getDiscountPrice
    discount = price
    prompts.each do |prompt|
      discount *= (prompt.activity.discount / 100.0)
    end
    discount
  end

  private
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

  def ensure_not_referenced_by_any_favor_item
    unless favor_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  belongs_to :product
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    "Buyer" => 0,
    "Admin" => 1
  }

  validates :name, presence: true, uniqueness: true
  validates :role, presence: true
  validates :role, inclusion: roles.keys
  has_secure_password

  has_many :favor_items, dependent: :destroy
  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = favor_items.find_by(product: product.id)

    if current_item
      # 查找到了，就数量增加 1，就啥都不干
    else
      # 没查找到，就创建 line_item
      current_item = favor_items.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes={}, &block)
    # 将 html 中具有 attributes 并满足 condition 条件的 div 设置为 display: none
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

<div>
  It's <%= Time.now %>
  We hava <%= pluralize(@total_orders, 'order') %><table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Pay Type</th>
    <th colspan='3'></th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.address %></td>
      <td><%= order.email %></td>
      <td><%= order.phone %></td>
      <td><%= order.pay_type %></td>
      <td><%= link_to 'Show', order %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
      <td><%= link_to 'Destroy', order, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>魔法补完计划</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class='<%= controller.controller_name %>'>
  <!-- 顶部栏 -->
  <div id="banner">
    <%= image_tag "logo.png", class: 'img1'%>
    <%= image_tag "logo2.png", class: 'img2'%>
    <!-- 普通链接 -->
    <div class="nav">
      <%= link_to '商店', store_index_url, class: 'nav_block' %>
      <%= link_to '收藏', favor_items_path, class: 'nav_block' %>
      <%= link_to '促销', activity_show_path, class: 'nav_block' %>
      <!-- 管理链接 -->
      <% if current_user and current_user.role == 'Admin' %>
        <%= link_to '订单', orders_path, class: 'admin_nav_block' %>
        <%= link_to '产品', products_path, class: 'admin_nav_block' %>
        <%= link_to '用户', users_path, class: 'admin_nav_block' %>
        <%= link_to '活动', activities_path, class: 'admin_nav_block' %>
      <% end %>
    </div>
    <%= image_tag "blood.png", class: 'img3'%>
  </div>

  <!-- 顶部导航栏之下的区域 -->
  <div id="columns">
    <!-- 侧边栏 -->
    <div id="side">
      <!-- 购物车 -->
      <div id="cart_border">
        <div id="cart">
          <% if @cart %>
            <%= render @cart %>
          <% end %>
        </div>
      </div>

      <% if current_user %>
        <div class="svg-wrapper">
          <svg height="60" width="320">
            <rect class="shape" height="60" width="320"/>
            <div class="text">
              <%= current_user.name %>
            </div>
          </svg>
        </div>
      <% end %>

      <!-- 登录登出 -->
      <div class="log">
        <% if current_user %>
          <%= link_to 'Logout', logout_path, method: :delete %>
        <% else %>
          Please <%= link_to 'Login', login_url %>
        <% end %>
      </div>
    </div>


    <!-- 主体 -->
    <div id="main">
      <!-- yield 似乎就是 ruby 中的 yield -->
      <%= yield %>
    </div>
  </div>
</body>
</html>