config/routes.rb
Rails.application.routes.draw do
  resources :prompts
  resources :activities
  resources :favor_items
  get 'admin' => 'admin#index'

  controller :activities do
    get 'activity_show' => :show_activity
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :prompts, dependent: :destroy

  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = prompts.find_by(product: product.id)

    if current_item
      # 查找到了，就啥都不干
    else
      # 没查找到，就创建 prompt
      current_item = prompts.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = line_items.find_by(product: product.id)

    if current_item
      # 查找到了，就数量增加 1
      current_item.quantity += 1
    else
      # 没查找到，就创建 line_item
      current_item = line_items.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/favor_item.rb
class FavorItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  # optional 表示外键可以为空
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    product.getDiscountPrice * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }

  has_many :line_items, dependent: :destroy

  validates :name, :address, :email, :phone, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # 对属性的检验
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {:greater_than_or_equal_to => 0.01}
  validates :title, uniqueness: true
  validates :image_url, format: {
    :with => %r{\.(gif|jpg|png)}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }

  # 与 line_item 关系
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :favor_items
  before_destroy :ensure_not_referenced_by_any_favor_item
  has_many :prompts, dependent: :destroy

  def getDiscountPrice
    discount = price
    prompts.each do |prompt|
      discount *= (prompt.activity.discount / 100.0)
    end
    discount
  end

  private
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

  def ensure_not_referenced_by_any_favor_item
    unless favor_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  belongs_to :product
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    "Buyer" => 0,
    "Admin" => 1
  }

  validates :name, presence: true, uniqueness: true
  validates :role, presence: true
  validates :role, inclusion: roles.keys
  has_secure_password

  has_many :favor_items, dependent: :destroy
  def add_product(product)
    # 根据 product_id 查找 current_item
    current_item = favor_items.find_by(product: product.id)

    if current_item
      # 查找到了，就数量增加 1，就啥都不干
    else
      # 没查找到，就创建 line_item
      current_item = favor_items.build(product_id: product.id)
    end
    # 返回 current_item
    current_item
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
    @orders = Order.all
  end
end

app/controllers/favor_items_controller.rb
class FavorItemsController < ApplicationController
  include CurrentCart
  before_action :set_favor_item, only: %i[ show edit update destroy ]
  before_action :set_user, only: [:create]
  before_action :set_cart
  # GET /favor_items or /favor_items.json
  def index
    @favor_items = FavorItem.all
  end

  # GET /favor_items/1 or /favor_items/1.json
  def show
  end

  # GET /favor_items/new
  def new
    @favor_item = FavorItem.new
  end

  # GET /favor_items/1/edit
  def edit
  end

  # POST /favor_items or /favor_items.json
  def create
    # 根据传入的 product_id 查找 product
    product = Product.find(params[:product_id])
    @favor_item = @user.add_product(product)

    respond_to do |format|
      if @favor_item.save
        format.html { redirect_to store_index_url }
        format.json { render :show, status: :created, location: @favor_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favor_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favor_items/1 or /favor_items/1.json
  def update
    respond_to do |format|
      if @favor_item.update(favor_item_params)
        format.html { redirect_to favor_item_url(@favor_item), notice: "Favor item was successfully updated." }
        format.json { render :show, status: :ok, location: @favor_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favor_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favor_items/1 or /favor_items/1.json
  def destroy
    @favor_item.destroy

    respond_to do |format|
      format.html { redirect_to favor_items_url, notice: "Favor item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favor_item
      @favor_item = FavorItem.find(params[:id])
    end

    def set_user
      @user = User.find(session[:user_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to store_index_url
    end
    # Only allow a list of trusted parameters through.
    def favor_item_params
      params.require(:favor_item).permit(:product_id, :user_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes={}, &block)
    # 将 html 中具有 attributes 并满足 condition 条件的 div 设置为 display: none
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/favor_items_helper.rb
module FavorItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favor_items/_favor_item.html.erb
<tr>
  <td>
    <%= image_tag(favor_item.product.image_url, class: 'list_image') %>
  </td>

  <td class="list_description">
    <dl>
      <dt><%= favor_item.product.title %></dt>
      <dd><%= strip_tags(favor_item.product.description) %></dd>
    </dl>
  </td>

  <td>
    <dl>
      <%= number_to_currency(favor_item.product.price) %>
    </dl>
    <dl>
      <%= button_to 'Add to Cart', line_items_path(product_id: favor_item.product), remote:true %>
    </dl>
    <dl>
      <%= button_to 'Remove', favor_item, :method => :delete %>
    </dl>
  </td>
</tr>

app/views/favor_items/_form.html.erb
<%= form_with(model: favor_item) do |form| %>
  <% if favor_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favor_item.errors.count, "error") %> prohibited this favor_item from being saved:</h2>

      <ul>
        <% favor_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/favor_items/edit.html.erb
<h1>Editing favor item</h1>

<%= render "form", favor_item: @favor_item %>

<br>

<div>
  <%= link_to "Show this favor item", @favor_item %> |
  <%= link_to "Back to favor items", favor_items_path %>
</div>

app/views/favor_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>收藏夹</h1>

<div id="favor_items">
  <table>
  <% @favor_items.each do |favor_item| %>
    <%= render favor_item %>
  <% end %>
  </table>
</div>

app/views/favor_items/new.html.erb
<h1>New favor item</h1>

<%= render "form", favor_item: @favor_item %>

<br>

<div>
  <%= link_to "Back to favor items", favor_items_path %>
</div>

app/views/favor_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favor_item %>

<div>
  <%= link_to "Edit this favor item", edit_favor_item_path(@favor_item) %> |
  <%= link_to "Back to favor items", favor_items_path %>

  <%= button_to "Destroy this favor item", @favor_item, method: :delete %>
</div>